#!/usr/bin/env php
<?php

/**
 * 获取命令参数
 */
function getArgv(){
    $data =$_SERVER['argv'];
}
var_dump(PHP_OS);

var_dump($_SERVER["argv"]);
//sudo ln -s /opt/homebrew/include/pcre2.h /opt/homebrew/Cellar/php@7.4/7.4.32/include/php/ext/pcre/pcre2.h

// yes --with-openssl-dir=/opt/homebrew/opt/openssl@1.1

