<?php


namespace ShiGuangXiaoTou\widgets;


use Yii;
use yii\base\Widget;


/**
 * 分类标签
 * @package ShiGuangXiaoTou\widgets
 */
class CategoryWidget extends Widget
{
    /**
     * 页面标题
     * @var $title
     */
    public $title;
    /**
     * 页面说明
     * @var $description
     */
    public $description;
    public $items=[];
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function run(){
        if(isset($this->description) and !empty($this->description)){
            return <<<HTML
<section>
    <div class="wrap">
        <h2>{$this->title}</h2>
        <p>{$this->description}</p>
        <ul class="flexblock features">
           {$this->renderItems()}
        </ul>
    </div>
</section>
HTML;
        }else{
            return <<<HTML
<section>
    <div class="wrap">
        <h2>{$this->title}</h2>
        <ul class="flexblock features">
           {$this->renderItems()}
        </ul>
    </div>
</section>
HTML;
        }

    }

    /**
     * @param $item
     * @return string
     */
    public function renderItem($item){
        if(isset($item["href"]) and !empty($item["href"])){
            return <<<HTML
<li>
    <a href="{$item["href"]}">
        <div>
            <h2>
                <svg class="{$item['icon']}">
                    <use xlink:href="#{$item['icon']}"></use>
                </svg>
                {$item['title']}
            </h2>
            {$item['description']}
        </div>
    </a>
</li>
HTML;
        }else{
            return <<<HTML
<li>
    <div>
        <h2>
            <svg class="{$item['icon']}">
                <use xlink:href="#{$item['icon']}"></use>
            </svg>
            {$item['title']}
        </h2>
        {$item['description']}
    </div>
</li>
HTML;
        }
    }

    /**
     * @return string
     */
    public function renderItems(){
        $i=1;
        $str='';
        foreach ($this->items as $item){
            if($i >9 ){
                return $str;
            }
            $str .= $this->renderItem($item);
        }
        return $str;
    }
}